#!/bin/sh
export XDG_SESSION_TYPE=x11
export GDK_BACKEND=x11

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmapi
export BROWSER="chromium"
export EDITOR="nvim"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.local/bin/statusbar"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
#export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
#export PATH="$PATH:$(du "$HOME/.local/bin" | cut -f2 | paste -sd ':')"
xset -dpms # Disables Energy Star features
xset s off # Disables screen saver
xrdb -merge .Xresources &
#picom &
nm-applet &
~/.fehbg &
dwmblocks &
#slstatus &
exec bspwm
#exec gnome-session
#exec xmonad
#exec dwm
#exec qtile
#exec awesome



 
