#! /bin/sh

bspc config border_width         1
bspc config window_gap           5
bspc config top_padding                   15
bspc config bottom_padding                -5
bspc config left_padding                  -5
bspc config right_padding                 -5

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config single_monocle true



bspc monitor DVI-I-1 -d 1 2 3 4 5 6 
bspc monitor HDMI-2 -d  7 8 9 10

##Color settings
#bspc config focused_border_color "#005577"
#bspc config normal_border_color "#222D32"
#bspc config presel_feedback_color "#1ABB9B"

bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"

#Floating applications
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Galculator state=floating center=true
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a St -e Htop state=floating center=true
bspc rule -a BleachBit state=floating center=true
bspc rule -a URxvt:urxvt_keys_help state=floating

#bspc rule -a firefox desktop='^2' 

sxhkd &
"$HOME"/.config/polybar/launch.sh &
#picom --config $HOME/.config/bspwm/picom.conf &

xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
~/.fehbg &
